# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pyfile\linedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.p1 = QtWidgets.QPushButton(Form)
        self.p1.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QPushButton(Form)
        self.p2.setGeometry(QtCore.QRect(110, 110, 75, 23))
        self.p2.setObjectName("p2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 110, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #点击鼠标
        self.pushButton.clicked.connect()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.p1.setText(_translate("Form", "复制"))
        self.p2.setText(_translate("Form", "删除"))
        self.pushButton.setText(_translate("Form", "清除"))

    def clice(self,Form):
        self.lineEdit.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
